SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `quizzes`;
TRUNCATE TABLE `quizzes_taken`;
TRUNCATE TABLE `friends`;
TRUNCATE TABLE `messages`;
TRUNCATE TABLE `badges`;
TRUNCATE TABLE `users_badges`;
TRUNCATE TABLE `question_response`;
TRUNCATE TABLE `question_response_correct_answers`;
TRUNCATE TABLE `fill_in_blank`;
TRUNCATE TABLE `fill_in_blank_correct_answers`;
TRUNCATE TABLE `multiple_choise`;
TRUNCATE TABLE `multiple_choise_answers`;
TRUNCATE TABLE `picture_response`;
TRUNCATE TABLE `picture_response_correct_answers`;
TRUNCATE TABLE `friend_requests`;
SET FOREIGN_KEY_CHECKS=1;
